[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
description = "Cross-platform library for managing passwords"
homepage = "https://github.com/hwchen/keyring-rs.git"
keywords = ["password", "cross-platform", "keychain", "keyring"]
license = "MIT OR Apache-2.0"
name = "bin"
repository = "https://github.com/hwchen/keyring-rs.git"
version = "0.5.0"
workspace = ".."

[dependencies]
clap = "*"
rpassword = "*"


[dependencies.keyring]
path = "../keyring"

[[bin]]
name = "keyring"
crate-type = ["bin"]
doctest = false
